spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.101.10:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

  jackson:
    default-property-inclusion: non_null


wechat:
  mpAppId: wx3194e8ef56908c1e
  mpAppSecret: 6025644c607655f4e7cd40414cef0ef9
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: E:/wechat/h5.p12
  notifyUrl: http://9zfdyb.natappfree.cc/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

project-url:
  wechatMpAuthorize: http://9zfdyb.natappfree.cc